services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.7
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
    ports:
      - "2181:2181"

  rest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-rest  
    ports:
      - "8080:8080"
    depends_on:
      - calculator
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9093
    networks:
      - app-network
  

  calculator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-calculator  
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9093
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

